### ISSUE TITLE
Vue loader for node_modules

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/webpack-vue-config#20]
It seems your excluding vue loader from dependencies. Any particular reason?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/webpack-vue-config/blob/ee6d264c4b54de89d5f495e1cd254c0b5b345099/package.json#L35

Am I ?

**Comment by marcelklehr** [comment]
Sorry, I mean in the webpack config, vue files in 'node_modules' are excluded.

**Comment by skjnldsv** [comment]
AH yes, because we don't want to pass any libs through this.
This is on pursose. We'rz all doing it since the beginning of the vue migrations :)

Did you experienced some issues?

**Comment by marcelklehr** [comment]
> Did you experienced some issues?

I was trying to import vue-material-ui-icons, which failed until I removed that exclude rule.

**Comment by skjnldsv** [comment]
It's the opposite, you need to only exclude the vue-material-ui-icons library as they're not exposing es modules but directly vue components. WHich luckily not many libs are doing :stuck_out_tongue: 
https://github.com/nextcloud/server/blob/9c1ee2e0ba84e7ad1f707bdf6080ec3df1680040/webpack.common.js#L84-L87

**Comment by marcelklehr** [comment]
Mh. Wouldn't it make sense to just enable that behavior for all node_modules, since the rule already checks if it's a .vue file?

**Comment by skjnldsv** [comment]
This still increase the compile time significantly! This is why we ignore what is not necessary and cherry pick what needs to be included.
Building server takes like 2 minutes. If we remove this rule, it suddenly goes up to 10 or something 😅

**Comment by marcelklehr** [comment]
Ah, I see your point. Nevermind, then. Thanks for the explanation :)

**Comment by skjnldsv** [comment]
You're welcome :)
