### ISSUE TITLE
Version 5 Release plan

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/webpack-vue-config#296]
@skjnldsv I started started to switch over to use the latest https://github.com/nextcloud/eslint-config etc. for polls and wanted to continue with webpack-vue-config, but the current 4.x release is incompatible to the latest versions of the other repos.  

Just for the planning; Is there a sheduled doa?

**Comment by skjnldsv** [comment]
Hi,

It seems I just forgot to release. I can't recall if that was intentional or not.
I just came back from vacations :see_no_evil:

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/webpack-vue-config/releases/tag/v5.0.0
