### ISSUE TITLE
Do not lint during build

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/webpack-vue-config#317]
It slows down local and CI build processes and should therefore be a separate process in my opinion.

**Comment by ChristophWurst** [comment]
I guess https://github.com/nextcloud/webpack-vue-config/blob/949133096424d54f42113d8cefc5105c8fa2efd8/webpack.config.js#L101-L105 needs to go for this. And then we could check if eslint is used at anywhere else and fully remove it from this package otherwise, right?

**Comment by juliushaertl** [comment]
Yes, maybe also for the stylelint plugin then which would also make sense to have separate I'd say.

**Comment by skjnldsv** [comment]
Yeah, we can remove both, I 100% agree :)
