### ISSUE TITLE
node-sass deprecated

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/webpack-vue-config#49]
> Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass.

https://www.npmjs.com/package/node-sass

The mentioned dart-sass package is the npm `sass` package:
https://www.npmjs.com/package/sass

**Comment by skjnldsv** [comment]
Depends on sass-loader https://github.com/webpack-contrib/sass-loader/blob/4caf60fb4a5e8f2d13cdde531e5277b0d2b9ab0b/package.json#L44
